version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - 8078:80
    depends_on:
      - app
    container_name: spa_comments_laravel_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
        - db
    container_name: spa_comments_laravel_app

  db:
    image: mysql:8.1
    restart: always
    volumes:
      - ./docker_db/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: spa_comments_laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
        - 3312:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: spa_comments_laravel_db
